name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Create .env file
      run: |
        echo "PORT=3200" >> .env
        echo "BINANCE_API_KEY=3zsP3b4WgikgXnRjspYuSLisJrePhH4XAL7ptjYWeykzNq7RDnRx8ZoegDDvZlMb" >> .env
        echo "BINANCE_API_SECRET=lS282ERiqgVYC7EXCAIxRp81X0oOMEYqEku8r9LbV1RH6Ub6EytE9tirrfE7QQCW" >> .env
    
    - name: Initialize Database
      run: npm run init-db
    
    - name: Fetch Historical Data
      run: npm run fetch-historical
    
    - name: Fetch Real-time Data
      run: npm run fetch-realtime
    
    - name: Run Machine Learning Predictions
      run: node scripts/ml-prediction.js
    
    - name: Install PM2
      run: npm install -g pm2
    
    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: 185.209.228.189
        username: root
        password: '@198711Ad@'
        source: "."
        target: "/var/www/html/kahin"
        strip_components: 0
        debug: true
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: 185.209.228.189
        username: root
        password: '@198711Ad@'
        script: |
          # Gerekli yazılımları kontrol et ve yükle
          if ! command -v node &> /dev/null; then
            curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
            yum install -y nodejs
          fi
          
          if ! command -v pm2 &> /dev/null; then
            npm install -g pm2
          fi
          
          # Uygulama dizinine git
          cd /var/www/html/kahin
          
          # Bağımlılıkları yükle
          npm ci
          
          # Veritabanını başlat
          npm run init-db
          
          # PM2 ile PORT=3200 üzerinden uygulamayı başlat
          pm2 delete kahin || true
          PORT=3200 pm2 start index.js --name kahin
        debug: true
        use_insecure_cipher: true